# Generated by Django 3.2.10 on 2021-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('nos', models.IntegerField()),
            ],
        ),
    ]
