# Generated by Django 3.2.10 on 2021-12-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uid',
        ),
    ]
